package com.tangtang.webviewcache;

public class Contacts {

    public static final String HTML = "<h1><span style=\"font-size:36px\">这款右斜纹牛仔连衣裙特别采用撕裂和修补、梭织贴布、刺绣和串珠细节，打造出 Polo 的专属风格。 </span></h1><ol><li><span style=\"font-size:36px\">上身修身下身宽松式廓形。长及膝盖。</span></li><li><span style=\"font-size:36px\">\u200BM 号尺码后衣长 41.9 厘米，胸围 102.9 厘米，腰围 88.9 厘米，臀围 105.4 厘米，袖长 61.0 厘米。每个尺码之间袖长相差 1.9 厘米。\u200B</span></li><li><span style=\"font-size:36px\">\u200B宽角领。纽扣式门襟。右领和衣襟采用对比色缝线。</span></li></ol><ul><li><span style=\"font-size:36px\">长袖，纽扣式单袖口。右侧袖子处有几何刺绣。左侧袖口有珠状刺绣。</span></li><li><span style=\"font-size:36px\"><span style=\"color:#d26b6b\">胸前两侧有纽扣式翻盖口袋。右侧口袋对比色翻盖。左胸、右臀和右肘处有撕裂和修补补片。右侧下摆处有法兰绒梭织补片。</span></span></li><li><span style=\"font-size:36px\"><em>背面有纽扣式腰袢。后左肩有小鸟刺绣。背后和后下摆做旧设计。左臀处有三个箭头刺绣。后下摆右侧有对比色补片。</em></span></li><li><span style=\"font-size:36px\"><span style=\"letter-spacing:2px\">外层：棉。撕裂和修补补片：棉、亚麻。</span></span></li><li><span style=\"font-size:36px\"><span style=\"line-height:1.5\">使用皮革专用清洁剂干洗。进口。</span></span></li><li><span style=\"font-size:64px\">模特身高 178 厘米，胸围 81.3 厘米，腰围 61.0 厘米，臀围 86.4 厘米。她穿 S 号尺码。</span></li><li><span style=\"font-size:36px\"><sub>产品图片及颜色可能因拍照光线、</sub>环境及角度误差或屏幕设定等影响，可能与实物产品颜色有所差异，请以实物为准。</span>\uD83D\uDC9B\uD83D\uDC9B\uD83D\uDC9A\uD83D\uDC9A</li></ul><ol><li>下面是网络图片</li></ol><p></p><div class=\"media-wrap image-wrap\"><img class=\"media-wrap image-wrap\" src=\"http://terminalfs.rongyi.com/system/prod/file/202207141509273451.jpg\" width=\"400px\" height=\"400px\" style=\"width:400px;height:400px\"/></div><p></p><ol><li>网络视频</li><li></li></ol><div class=\"media-wrap video-wrap\"><video controls=\"\" class=\"media-wrap video-wrap\" src=\"http://terminalfs.rongyi.com/system/prod/file/202206281656208323.mp4\"></video></div><p></p><pre><code>&lt;video width=&quot;320&quot; height=&quot;240&quot; controls&gt;<br/>  &lt;source src=&quot;movie.mp4&quot;  type=&quot;video/mp4&quot;&gt;<br/>  &lt;source src=&quot;movie.ogg&quot;  type=&quot;video/ogg&quot;&gt;<br/>  您的浏览器不支持 HTML5 video 标签。<br/>&lt;/video&gt;</code></pre>";

    public static String APP_ROOT_PATH = AppApplication.getContext().getFilesDir().getAbsolutePath() + "/cache/file/";

}
